### PR TITLE
update common to latest

### PR DESCRIPTION
**Pull request by kaisong1990**
Update to use the latest common core

## Type of change

- [ ] Feature work
- [ ] Bug fix
- [ ] Documentation
- [ ] Engineering change
- [ ] Test
- [ ] Logging/Telemetry

## Risk

- [ ] High – Errors could cause MAJOR regression of many scenarios. (Example: new large features or high level infrastructure changes)
- [ ] Medium – Errors could cause regression of 1 or more scenarios. (Example: somewhat complex bug fixes, small new features)
- [x ] Small – No issues are expected. (Example: Very small bug fixes, string changes, or configuration settings changes)

### CODE REVIEW

**Comment by hieunguyenmsft** [comment]
Hi @kaisong1990, just for my learning: I see Travis build is failed. Is it because of the new code change or that's another issue not related to this commit?

**Comment by hieunguyenmsft** [comment]
For my learning, too (for some reason I cannot added the comment into these change files directly, so I just paste it here):

 ```
   [results sortUsingComparator:^NSComparisonResult(MSIDBaseToken *obj1, MSIDBaseToken *obj2)
    {
        return obj1.clientId > obj2.clientId;
    }];
```
I'm new to obj-c, just wonder what will happen if any obj1 or obj2 is nil?

**Comment by kaisong1990** [comment]
> Hi @kaisong1990, just for my learning: I see Travis build is failed. Is it because of the new code change or that's another issue not related to this commit?

Hi Hieu, thanks for your question. The issue is related to what I mentioned in scrum that Travis will check the __unused tag but the common core doesn't. So I missed that tag and caused a failure. Here is a [fix](https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/pull/772) in common core to add __unused tag.

**Comment by hieunguyenmsft** [comment]
> Hi Hieu, thanks for your question. The issue is related to what I mentioned in scrum that Travis will check the __unused tag but the common core doesn't. So I missed that tag and caused a failure. Here is a [fix](https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/pull/772) in common core to add __unused tag.
Great, thank you!

**Comment by kaisong1990** [comment]
> For my learning, too (for some reason I cannot add the comment into these change files directly, so I just paste it here):
> 
> ```
>   [results sortUsingComparator:^NSComparisonResult(MSIDBaseToken *obj1, MSIDBaseToken *obj2)
>    {
>        return obj1.clientId > obj2.clientId;
>    }];
> ```
> 
> I'm new to obj-c, just wonder what will happen if any obj1 or obj2 is nil?

Just a little background of this:

When retrieving items from keychain/cache into an array, the order is not guaranteed. However, in our UT, we make the assumption that the order is always like that which works fine in Xcode 11, but somehow the order got changed in Xcode 12 which caused failures. 

By applying the manually comparator here, we can guarantee the order within the array based on alphabetic in both xcode versions

**Pull request merged**
