### PR TITLE
Submodule update for CommonCore to support XPC work

### PR DESCRIPTION
**Pull request by kaisong1990**
## Proposed changes

Update commonCore to support Broker XPC

## Type of change

- [x] Feature work
- [ ] Bug fix
- [ ] Documentation
- [ ] Engineering change
- [ ] Test
- [ ] Logging/Telemetry

## Risk

- [ ] High – Errors could cause MAJOR regression of many scenarios. (Example: new large features or high level infrastructure changes)
- [ ] Medium – Errors could cause regression of 1 or more scenarios. (Example: somewhat complex bug fixes, small new features)
- [ ] Small – No issues are expected. (Example: Very small bug fixes, string changes, or configuration settings changes)

### CODE REVIEW

**Comment by ameyapat** [comment]
Cloned PR for kasong/2914059-telemetry

----
#### AI description  (iteration 1)
#### PR Classification
New feature and bug fix.

#### PR Summary
This pull request introduces a new CI pipeline configuration and fixes the order of method calls in several request classes.
- Added `msal_submodule_check.yaml` to configure CI pipeline for PR validation and main/release branch triggers.
- Fixed the order of `msidPerformRequests` method calls in `MSIDSSOExtensionGetAccountsRequest.m`, `MSIDSSOExtensionGetDeviceInfoRequest.m`, `MSIDSSOExtensionInteractiveTokenRequest.m`, `MSIDSSOExtensionSignoutRequest.m`, and `MSIDSSOExtensionSilentTokenRequest.m`.
- Added `MSID_BROKER_SDK_BROKER_XPC_CAPABILITY` constant in `MSIDBrokerConstants.h` and `MSIDBrokerConstants.m`.
- Added `requestType` property in `MSIDBaseBrokerOperationRequest.h`.

**Review by juan-arias — APPROVED** [review]

**Comment by ameyapat** [comment]
Cloned PR for kasong/2914059-telemetry

----
#### AI description  (iteration 1)
#### PR Classification
New feature

#### PR Summary
This pull request introduces a new capability for broker XPC communication and adds a new property to the broker operation request.
- `MSIDBrokerConstants.h` and `MSIDBrokerConstants.m`: Added `MSID_BROKER_SDK_BROKER_XPC_CAPABILITY` constant.
- `MSIDBaseBrokerOperationRequest.h`: Added `requestType` property.

**Comment by ameyapat** [comment]
"Added `1` Inline Code Review comment(s) at the following location(s):
- **/msal-from-github/MSAL/IdentityCore/IdentityCore/src/broker_operation/request/MSIDBaseBrokerOperationRequest.h** at Line 36

AI-generated content may be incorrect
"

**Comment by ameyapat** [comment]
"
    
        
        AI Code Review
        
    
    
        
        Iteration
        1
        
    
    
        
        Readability: Encapsulation
        
    

## Task 1
It might be better to make the `requestType` property `readonly` if it is not intended to be modified after initialization. This can help prevent unintended changes to the property and improve the immutability of the class.

Here is the suggested code:
```objective-c
@property (nonatomic, readonly) NSInteger requestType;
```
This comment refers to line 36 to 36 in the new file.

## Task 2
2
AI-generated content may be incorrect

**Pull request merged**
