### PR TITLE
Bring in latest common core and make related pipelines running on Xcode 12

### PR DESCRIPTION
**Pull request by kaisong1990**
## Proposed changes

Describe what this PR is trying to do.

## Type of change

- [ ] Feature work
- [ ] Bug fix
- [ ] Documentation
- [ ] Engineering change
- [X] Test
- [ ] Logging/Telemetry

## Risk

- [ ] High – Errors could cause MAJOR regression of many scenarios. (Example: new large features or high level infrastructure changes)
- [ ] Medium – Errors could cause regression of 1 or more scenarios. (Example: somewhat complex bug fixes, small new features)
- [X] Small – No issues are expected. (Example: Very small bug fixes, string changes, or configuration settings changes)

### CODE REVIEW

**Review by NerevarineRule — APPROVED** [review]
@kaisong1990  Just for my learning purpose. What are some of the pros and cons of the YML vs existing Azure Pipeline?

**Comment by kaisong1990** [comment]
> @kaisong1990 Just for my learning purpose. What are some of the pros and cons of the YML vs existing Azure CI/CD check that rely on command line & python script, etc.?

YML file is like an instruction for Azure pipelines on what tasks needed to be done in which environment. In other words, Azure pipelines can use YML file to run its job. The python files are the scrips telling xcode to compile/run tests based on certain configuration.

**Comment by NerevarineRule** [comment]
@kaisong1990 Thanks Kai. I guess what I also wanted to ask was does it offer additional capabilities that cannot be achieved through command line script?  There are two types that I see in the pipeline - rocket (CMD?) and bearded guy (Travis). Just wanted to see if the other one offers additional capability over another was all haha.

**Comment by kaisong1990** [comment]
> @kaisong1990 Thanks Kai. I guess what I also wanted to ask was does it offer additional capabilities that cannot be achieved through command line script? There are two types that I see in the pipeline - rocket (CMD?) and bearded guy (Travis). Just wanted to see if the other one offers additional capability over another was all haha.

Rocket is Azure Pipeline and bearded is James Harden :) 

Both are CI
Azure Pipeline is much faster compared to Travis based on the observation 
External contributors can access the logs from Travis but not Azure Pipeline (Will need a MS account and added as a member)

travis.yml is for travis CI only, and you can configure different job from Azure Pipeline or create separate yml files

**Comment by NerevarineRule** [comment]
@kaisong1990  Thank you :)

**Pull request merged**
