### PR TITLE
Update CI/CD and automation to use Xcode 14 instead of Xcode 13 (MSAL)

### PR DESCRIPTION
**Pull request by antonioalwan**
## Proposed changes

Update build pipeline and automation pipeline to macOS-13
Note that few tests are failing are the same as dev. Need separate investigation

## Type of change

- [x] Feature work
- [ ] Bug fix
- [ ] Documentation
- [ ] Engineering change
- [ ] Test
- [ ] Logging/Telemetry

## Risk

- [ ] High – Errors could cause MAJOR regression of many scenarios. (Example: new large features or high level infrastructure changes)
- [ ] Medium – Errors could cause regression of 1 or more scenarios. (Example: somewhat complex bug fixes, small new features)
- [x] Small – No issues are expected. (Example: Very small bug fixes, string changes, or configuration settings changes)

## Additional information
https://identitydivision.visualstudio.com/Engineering/_workitems/edit/2502860

### CODE REVIEW

**Comment by oldalton** [comment]
`Note that few tests are failing are the same as dev. Need separate investigation
`
Are those CIAM tests that are failing?

**Comment by antonioalwan** [comment]
@oldalton In regards to failing tests. Yes they are the CIAM/B2C tests:
```bash
Failing tests:
-[MSALB2CInteractiveTests testInteractiveB2CLogin_withEmbeddedWebView_withoutLoginHint_withSigninPolicy_withGUIDTenantId_withMSAAccount]
-[MSALB2CInteractiveTests testInteractiveB2CLogin_withEmbeddedWebView_withoutLoginHint_withSigninPolicy_withTenantName_withMSAAccount]
-[MSALB2CInteractiveTests testInteractiveB2CLogin_withPassedInWebView_withoutLoginHint_withSigninAndProfilePolicies_withTenantName_withMSAAccount]
-[MSALB2CInteractiveTests testInteractiveB2CLogin_withSafariViewController_withoutLoginHint_withSigninPolicy_withMSAAccount]
-[MSALCIAMAuthorityTests testInteractiveAndSilentCIAMLogin_withPromptAlways_noLoginHint_andSystemWebView]
-[MSALCIAMTest testInteractiveAndSilentCIAMLogin_withPromptAlways_noLoginHint_andSystemWebView]
-[MSALCIAMTest testInteractiveAndSilentCIAMLogin_withPromptAlways_noLoginHint_andSystemWebView]
-[MSALCIAMTest testInteractiveAndSilentCIAMLogin_withPromptAlways_noLoginHint_andSystemWebView]
```

**Comment by oldalton** [comment]
> @oldalton In regards to failing MSAL automation tests. Yes they are the CIAM/B2C tests:
> 
> ```shell
> Failing tests:
> -[MSALB2CInteractiveTests testInteractiveB2CLogin_withEmbeddedWebView_withoutLoginHint_withSigninPolicy_withGUIDTenantId_withMSAAccount]
> -[MSALB2CInteractiveTests testInteractiveB2CLogin_withEmbeddedWebView_withoutLoginHint_withSigninPolicy_withTenantName_withMSAAccount]
> -[MSALB2CInteractiveTests testInteractiveB2CLogin_withPassedInWebView_withoutLoginHint_withSigninAndProfilePolicies_withTenantName_withMSAAccount]
> -[MSALB2CInteractiveTests testInteractiveB2CLogin_withSafariViewController_withoutLoginHint_withSigninPolicy_withMSAAccount]
> -[MSALCIAMAuthorityTests testInteractiveAndSilentCIAMLogin_withPromptAlways_noLoginHint_andSystemWebView]
> -[MSALCIAMTest testInteractiveAndSilentCIAMLogin_withPromptAlways_noLoginHint_andSystemWebView]
> -[MSALCIAMTest testInteractiveAndSilentCIAMLogin_withPromptAlways_noLoginHint_andSystemWebView]
> -[MSALCIAMTest testInteractiveAndSilentCIAMLogin_withPromptAlways_noLoginHint_andSystemWebView]
> ```

I think it's expected that CIAM tests fail, but not B2C tests. Is it a recent failure?

**Comment by antonioalwan** [comment]
> 

Seems that since May 13 a whole set of [test failures](https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=1101100&view=logs&j=d1fe9029-a94c-5714-8677-3a82b24ad11b&t=e0aafc62-0fb0-511c-8548-87aea0a99d4a) were introduced after [PR#1739](https://github.com/AzureAD/microsoft-authentication-library-for-objc/pull/1739) Which is related to Merging release 1.2.12 back into dev.
But then after [PR#1731 ](https://github.com/AzureAD/microsoft-authentication-library-for-objc/pull/1731) the tests errors got [reduced to B2C and CIAM](https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=1104859&view=logs&j=d1fe9029-a94c-5714-8677-3a82b24ad11b&t=e0aafc62-0fb0-511c-8548-87aea0a99d4a)

**Comment by oldalton** [comment]
> 

What error do B2C tests fail with? This sounds problematic to me

**Comment by antonioalwan** [comment]
> What error do B2C tests fail with? This sounds problematic to me

Added the following Workitem with details:
https://identitydivision.visualstudio.com/Engineering/_workitems/edit/2590053

**Comment by oldalton** [comment]
> 

So, I think a bunch of test failures came from an expired conf file. Conf file got fixed then, but Veena's PR seems to be the one that introduced a breakage in B2C tests. @Veena11, could you take a look and see if that's the case? I see those B2C tests succeeding in last release, and there doesn't seem to be many other changes happening since then.

**Review by oldalton — APPROVED** [review]

**Pull request merged**
