### PR TITLE
Update SFAuthenticationSession branch with dev branch

### PR DESCRIPTION
**Pull request by xerners**
A customer wants to use SFAuthenticationSession for SSO. This is to see how painful it would be to merge dev with this code. It looks like there are no conflicts.

### CODE REVIEW

**Comment by xerners** [comment]
A customer wants to use SFAuthenticationSession for SSO. This is to see how painful it would be to merge dev with this code. It looks like there are no conflicts.

**Comment by oldalton** [comment]
@xerners I don't think we should point customer to this code as this was merely for testing/experimentation purposes.

**Comment by xerners** [comment]
I understand that concern. Is it fair to tell the customer that this an experimental branch and not part of the production supported preview, but they can use it at their own risk? Pointing customers to in-progress branches is exactly what we should be doing for both their guidance, feedback, and help.

**Comment by xerners** [comment]
I'm happy to share the customer, but not here obviously :-)

**Comment by xerners** [comment]
Removing due to strategy change

**Pull request closed without merging**
