### PR TITLE
Add support to attach cross domain PRT in embedded webview

### PR DESCRIPTION
**Pull request by jasoncoolmax**
## Proposed changes

Describe what this PR is trying to do.

## Type of change

- [x] Feature work
- [ ] Bug fix
- [ ] Documentation
- [ ] Engineering change
- [ ] Test
- [ ] Logging/Telemetry

## Risk

- [ ] High – Errors could cause MAJOR regression of many scenarios. (Example: new large features or high level infrastructure changes)
- [x] Medium – Errors could cause regression of 1 or more scenarios. (Example: somewhat complex bug fixes, small new features)
- [ ] Small – No issues are expected. (Example: Very small bug fixes, string changes, or configuration settings changes)

### CODE REVIEW

**Comment by ameyapat** [comment]
Cloned PR for zeyong/WebviewCrossDomainPrtAttach

----
#### AI description  (iteration 1)
#### PR Classification
New feature

#### PR Summary
This pull request introduces custom header support for webview requests and updates the handling of URL opening methods.
- `MSIDOAuth2EmbeddedWebviewController.m`: Added logic to inject custom headers into webview requests.
- `MSIDCustomHeaderProviding.h`: Introduced a new protocol for providing custom headers.
- `MSIDAppExtensionUtil.m`: Replaced deprecated `UIApplication.openURL(_:)` method with a new approach.
- `MSIDAadAuthorityCache.m` and related files: Added support for tracking cloud network environments.
- `MSIDDefaultTokenCacheAccessor.m`: Updated method to include account identifier in token queries.

**Comment by ameyapat** [comment]
"Added `1` Inline Code Review comment(s) at the following location(s):
- **/msal-from-github/MSAL/IdentityCore/IdentityCore/src/webview/embeddedWebview/customHeaderProviding/MSIDCustomHeaderProviding.h** at Lines 31-32

AI-generated content may be incorrect
"

**Review by oldalton — APPROVED** [review]

**Comment by ameyapat** [comment]
Cloned PR for zeyong/WebviewCrossDomainPrtAttach

----
#### AI description  (iteration 1)
#### PR Classification
New feature

#### PR Summary
This pull request introduces support for custom headers in webview requests and improves cross-cloud authentication.
- `MSIDOAuth2EmbeddedWebviewController.m`: Added logic to handle custom headers in webview requests.
- `MSIDCustomHeaderProviding.h`: New interface for providing custom headers.
- `MSIDDefaultTokenCacheAccessor.m`: Added method to get primary refresh tokens for a specific account.
- `MSIDAadAuthorityCache.m`: Added support for tracking cloud network environments.
- `MSALNativeAuthUserAccountEndToEndTests.swift`: Added tests for access token refresh and sign-in with different scopes.

**Comment by ameyapat** [comment]
Cloned PR for zeyong/WebviewCrossDomainPrtAttach

----
#### AI description  (iteration 1)
#### PR Classification
New feature

#### PR Summary
This pull request introduces support for custom headers in webview requests and enhances cross-cloud authentication.
- `MSIDOAuth2EmbeddedWebviewController.m`: Added logic to handle custom headers in webview requests.
- `MSIDCustomHeaderProviding.h`: New protocol for providing custom headers.
- `MSIDDefaultTokenCacheAccessor.m`: Added method to get primary refresh tokens for a specific account.
- `MSIDAadAuthorityCache.m`: Updated to store and return all cloud network environments.
- `MSALNativeAuthUserAccountEndToEndTests.swift`: Added tests for sign-in and token refresh scenarios.

**Pull request merged**
