### PR TITLE
Merge Release/1.1.15 back to dev

### PR DESCRIPTION
**Pull request by jasoncoolmax**
## Proposed changes

Merge Release/1.1.15 back to dev

## Type of change

- [ ] Feature work
- [ ] Bug fix
- [ ] Documentation
- [x] Engineering change
- [ ] Test
- [ ] Logging/Telemetry

## Risk

- [ ] High – Errors could cause MAJOR regression of many scenarios. (Example: new large features or high level infrastructure changes)
- [ ] Medium – Errors could cause regression of 1 or more scenarios. (Example: somewhat complex bug fixes, small new features)
- [x] Small – No issues are expected. (Example: Very small bug fixes, string changes, or configuration settings changes)

### CODE REVIEW

**Comment by ameyapat** [comment]
@jasoncoolmax I think fe8c307f0a24b6f533d2c2209455fa66ad249752 will be missed being included in dev after merging this PR. We might need to open a branch from fe8c307f0a24b6f533d2c2209455fa66ad249752 and merge it into dev instead?

**Comment by kaisong1990** [comment]
> @jasoncoolmax I think [fe8c307](https://github.com/AzureAD/microsoft-authentication-library-for-objc/commit/fe8c307f0a24b6f533d2c2209455fa66ad249752) will be missed being included in dev after merging this PR. We might need to open a branch from [fe8c307](https://github.com/AzureAD/microsoft-authentication-library-for-objc/commit/fe8c307f0a24b6f533d2c2209455fa66ad249752) and merge it into dev instead?

Do we have different commits in release branch?

**Comment by ameyapat** [comment]
> > @jasoncoolmax I think [fe8c307](https://github.com/AzureAD/microsoft-authentication-library-for-objc/commit/fe8c307f0a24b6f533d2c2209455fa66ad249752) will be missed being included in dev after merging this PR. We might need to open a branch from [fe8c307](https://github.com/AzureAD/microsoft-authentication-library-for-objc/commit/fe8c307f0a24b6f533d2c2209455fa66ad249752) and merge it into dev instead?
> 
> Do we have different commits in release branch?

Yes, after the release branch is merged into master, the release pipeline makes this commit on master to modify Package.swift file with version number and checksum for MSAL framework. In this case the only file differing between master and dev(and release) will be Package.swift so not a big deal just that it will be inconsistent.

**Comment by jasoncoolmax** [comment]
@ameyapat  you are right, another PR created. I will also update the release procedure :)

**Pull request closed without merging**
